### ISSUE TITLE
WX

### ISSUE THREAD

**Issue by a3li** [a3li/atciss#12]
NOAA-METAR/TAF für alles und jeden vorhalten (cache und refresh)
+ VATSIM-METAR als Vergleich, falls NOAA aktueller ist

**Comment by fpletz** [comment]
- https://tgftp.nws.noaa.gov/data/observations/metar/
- https://www.aviationweather.gov/help/webservice?page=metarjson
- https://metar.vatsim.net/?id=EDDM
